package no.kristiania.http;

import java.util.HashMap;
import java.util.Map;

public class MimeTypes {
    public static final Map<String,String> mimeTypeList = new HashMap<>();

    static {
        mimeTypeList.put(".acc", "audio/acc");
        mimeTypeList.put(".abw","application/x-abiword");
        mimeTypeList.put(".arc","application/x-freearc");
        mimeTypeList.put(".avi","video/x-msvideo");
        mimeTypeList.put(".azw","application/vnd.amazon.ebook");
        mimeTypeList.put(".bin","application/octet-stream");
        mimeTypeList.put(".bmp","image/bmp");
        mimeTypeList.put(".bz","application/x-bzip");
        mimeTypeList.put(".bz2","application/x-bzip2");
        mimeTypeList.put(".csh","application/x-csh");
        mimeTypeList.put(".css","text/css");
        mimeTypeList.put(".csv","text/csv");
        mimeTypeList.put(".doc","application/msword");
        mimeTypeList.put(".docx","application/vnd.openxmlformats-officedocument.wordprocessingml.document");
        mimeTypeList.put(".eot","application/vnd.ms-fontobject");
        mimeTypeList.put(".epub","application/epub+zip");
        mimeTypeList.put(".gz","application/gzip");
        mimeTypeList.put(".gif","image/gif");
        mimeTypeList.put(".htm","text/html");
        mimeTypeList.put(".html","text/html");
        mimeTypeList.put(".ico","image/vnd.microsoft.icon");
        mimeTypeList.put(".ics","text/calendar");
        mimeTypeList.put(".jar","application/java-archive");
        mimeTypeList.put(".jpeg","image/jpeg");
        mimeTypeList.put(".jpg","image/jpeg");
        mimeTypeList.put(".js","text/javascript");
        mimeTypeList.put(".json","application/json");
        mimeTypeList.put(".jsonld","application/ld+json");
        mimeTypeList.put(".mid","audio/midi");
        mimeTypeList.put(".midi","audio/x-midi");
        mimeTypeList.put(".mjs","text/javascript");
        mimeTypeList.put(".mp3","audio/mpeg");
        mimeTypeList.put(".mpeg","video/mpeg");
        mimeTypeList.put(".mpkg","application/vnd.apple.installer+xml");
        mimeTypeList.put(".odp","application/vnd.oasis.opendocument.presentation");
        mimeTypeList.put(".ods","application/vnd.oasis.opendocument.spreadsheet");
        mimeTypeList.put(".odt","application/vnd.oasis.opendocument.text");
        mimeTypeList.put(".oga","audio/ogg");
        mimeTypeList.put(".ogv","video/ogg");
        mimeTypeList.put(".ogx","application/ogg");
        mimeTypeList.put(".otf","font/otf");
        mimeTypeList.put(".png","image/png");
        mimeTypeList.put(".pdf","application/pdf");
        mimeTypeList.put(".php","application/php");
        mimeTypeList.put(".ppt","application/vnd.ms-powerpoint");
        mimeTypeList.put(".pptx","application/vnd.openxmlformats-officedocument.presentationml.presentation");
        mimeTypeList.put(".rar","application/x-rar-compressed");
        mimeTypeList.put(".rtf","application/rtf");
        mimeTypeList.put(".sh","application/x-sh");
        mimeTypeList.put(".svg","image/svg+xml");
        mimeTypeList.put(".swf","application/x-shockwave-flash");
        mimeTypeList.put(".tar","application/x-tar");
        mimeTypeList.put(".tif","image/tiff");
        mimeTypeList.put(".tiff","image/tiff");
        mimeTypeList.put(".ts","video/mp2t");
        mimeTypeList.put(".ttf","font/ttf");
        mimeTypeList.put(".txt","text/plain");
        mimeTypeList.put(".vsd","application/vnd.visio");
        mimeTypeList.put(".wav","audio/wav");
        mimeTypeList.put(".weba","audio/webm");
        mimeTypeList.put(".webm","video/webm");
        mimeTypeList.put(".webp","image/webp");
        mimeTypeList.put(".woff","font/woff");
        mimeTypeList.put(".woff2","font/woff2");
        mimeTypeList.put(".xhtml","application/xhtml+xml");
        mimeTypeList.put(".xls","application/vnd.ms-excel");
        mimeTypeList.put(".xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
        mimeTypeList.put(".xml","text/xml");
        mimeTypeList.put(".xul","application/vnd.mozilla.xul+xml");
        mimeTypeList.put(".zip","application/zip");
        mimeTypeList.put(".3gp","video/3gpp");
        mimeTypeList.put(".3g2","video/3gpp2");
        mimeTypeList.put(".7z","application/x-7z-compressed");
    }
}
